apiVersion: v1
kind: Service
metadata:
  name: scrapewatch
  labels:
    app: scrapewatch
spec:
  selector:
    app: scrapewatch
  type: LoadBalancer
  ports:
  - name: service
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: chrome
    protocol: TCP
    port: 4444
    targetPort: 4444
