apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapewatch
  labels:
    app: scrapewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapewatch
  template:
    metadata:
      labels:
        app: scrapewatch
    spec:
      containers:
      - name: scrapewatch
        image: natanasov1994/scrapewatch:9
        env:
          - name: WEB_DRIVER_LOCATION
            value: http://localhost:4444
        livenessProbe:
          initialDelaySeconds: 120
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8080
      - name: scrapewatch-chrome
        image: selenium/standalone-chrome:117.0
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
        ports:
          - containerPort: 4444