apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapewatch
  labels:
    app: scrapewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapewatch
  template:
    metadata:
      labels:
        app: scrapewatch
    spec:
      containers:
      - name: scrapewatch
        image: natanasov1994/scrapewatch:2
        resources:
          limits:
            memory: 256Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "0.2"
        ports:
        - containerPort: 8080