apiVersion: v1
kind: Service
metadata:
  name: scrapewatch
  labels:
    app: scrapewatch
spec:
  selector:
    app: scrapewatch
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
