apiVersion: v1
kind: Service
metadata:
  name: scrapewatch-ui
  labels:
    app: scrapewatch-ui
spec:
  selector:
    app: scrapewatch-ui
  type: LoadBalancer
  ports:
  - name: service
    protocol: TCP
    port: 80
    targetPort: 80
  - name: prometheus-exporter
    protocol: TCP
    port: 9113
    targetPort: 9113
