apiVersion: v1
kind: Service
metadata:
  name: scrapewatch-ui
  labels:
    app: scrapewatch-ui
spec:
  selector:
    app: scrapewatch-ui
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
